{
 "title": "Angeloni - CSC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Agendamentos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(agendamentos_total) by (status)"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(downloads_total) by (status)"
    }
   ]
  },
  {
   "title": "Pedidos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(pedidos_total) by (status)" }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jobs_total) by (name, status)"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(notifications_total) by (status)"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Angeloni CSC API",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds{uri=~\"/api/.*\",quantile=\"0.5\"}) by (method, uri, outcome)  ",
     "legendFormat": "avg {{method}} {{uri}} {{outcome}}"
    },
    {
     "expr": "max(http_server_requests_seconds{uri=~\"/api/.*\",quantile=\"0.95\"}) by (method, uri, outcome)  ",
     "legendFormat": "p95 {{method}} {{uri}} {{outcome}}"
    }
   ]
  },
  {
   "title": "AgendaEntrega API",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_client_requests_seconds{quantile=\"0.5\"}) by (method, uri, status)",
     "legendFormat": "avg {{method}} {{uri}} {{status}}"
    },
    {
     "expr": "max(http_client_requests_seconds{quantile=\"0.95\"}) by (method, uri, status)",
     "legendFormat": "p95 {{method}} {{uri}} {{status}}"
    }
   ]
  }
 ]
}